[http]
host = "0.0.0.0"
port = 8080
workers = 0
keep_alive_timeout = 15
tls = false
tls_key_file = ""
tls_cert_file = ""

[misc]
# How many characters generated keys should be
keylength = 6

[content]
# Maximum size of uploads, in MB
maxsize = 10
gzip_compression_level = 1
